config/routes.rb
AssistantHarmony::Application.routes.draw do
  get   "/register"                => "sessions#new",    as: :register
  match "/auth/:provider/callback" => "sessions#create", as: :register_callback

  resource :profile, only: [:show, :update] do
    resources :assignments, only: [:index, :show, :create, :destroy] do
      member do
        get :schedule
      end
    end

    resources :meetings, only: [] do
      member do
        get :reject
        get :schedule
      end
    end

    resources :calendars, only: [:subscribe] do
      get :subscribe
    end

    get :load
  end

  root to: "profiles#show"
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :user_id, :schedule_start_at

  validates :user_id,   presence: true

  belongs_to :user
  has_many :meetings, dependent: :destroy
  has_many :recipients, dependent: :destroy

  def schedule_meetings(options = {increment: 1.hour, amount: 3})
    options[:amount].to_i.times do
      while !schedule(increment: options[:increment])
        puts "executing schedule, meeting already exists"
      end
    end
  end

  def google_busy_events
    return @google_busy_events if @google_busy_events

    google = GoogleService.new(user, {name: 'calendar', version: 'v3'})
    json = JSON.parse(google.query({
      method: google.service.freebusy.query,
      body: {
        items: user.selected_calendars.map{ |c| {id: c.external_id} },
        timeMin: schedule_start_at.to_s(:rfc3339),
        timeMax: (schedule_start_at + 7.days).to_s(:rfc3339)
      }
    }).response.env[:body])

    @google_busy_events = json["calendars"]
                            .map{ |id, busy_events| busy_events["busy"] }
                            .flatten
                            .sort{ |a,b| a["start"] <=> b["start"] }
  end

  def meeting_exists?(meeting)
    meetings.detect{|m| m.start_at == meeting.start_at && m.end_at == meeting.end_at}.present?
  end

  def schedule(options = {})
    success = false

    meeting = options[:meeting] || random_meeting(options[:increment])

    unless meeting_exists?(meeting)
      meetings << meeting
      success = true
    end

    success
  end

  def random_meeting(increment = 1.hour, range_increment = 7.days)
    start_at = DateTime.parse("#{random_date(range_increment)} #{random_time}")

    Meeting.new do |meeting|
      meeting.user_id = self.user_id
      meeting.key = SecureRandom.uuid
      meeting.start_at = start_at
      meeting.end_at = start_at + increment
    end
  end

  def random_date(increment = 7.days)
    rand (schedule_start_at.to_date)..(schedule_start_at.to_date + increment)
  end

  def random_time
    rand 8..18 # Derive this from the user profile later
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_filter :authenticate

  def index
    @assignments = current_user.assignments.order('created_at asc')
  end

  def show
    @zone = ActiveSupport::TimeZone.new("Central Time (US & Canada)")
    @assignment = current_user.assignments.find(params[:id])
    @meetings = @assignment.meetings.order('start_at')
  end

  def create
    Rails.logger.info params[:assignment].merge(user_id: current_user.id)

    recipients = params[:assignment].delete(:recipient).split(",").map do |email|
      Recipient.new(email: email)
    end

    @assignment = Assignment.new(params[:assignment].merge({
      user_id: current_user.id, schedule_start_at: Time.now + 1.day
    }))

    recipients.each do |recipient|
      @assignment.recipients << recipient
    end
    
    if @assignment.save
      redirect_to profile_assignments_path
    end
  end

  def destroy
    user = current_user.assignments.find(params[:id])
    user.destroy

    redirect_to profile_assignments_path
  end

  def schedule
    assignment = current_user.assignments.find(params[:id])

    if assignment
      assignment.schedule_meetings({
        increment: 1.hour, amount: params[:amount] || 3
      })
      redirect_to profile_assignment_path(assignment)
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
  def reject_link_for(meeting)
    if meeting.state == "suggested"
      link_to 'reject', reject_profile_meeting_path(meeting.key)
    else
      'reject'
    end
  end

  def schedule_link_for(meeting)
    if meeting.state == "suggested"
      link_to 'schedule', schedule_profile_meeting_path(meeting.key)
    else
      'schedule'
    end
  end

  def matched(meetings, zone, time)
    meetings.detect do |meeting|
      meeting.start_at == time - 5.hours
    end
  end

  def first(meetings)
    meetings.first.start_at.to_i
  end

  def last(meetings)
    meetings.last.start_at.to_i
  end

  def iterate(meetings, increment = 1.hour)
    hour = first(meetings)
    ending = last(meetings)

    while hour < ending
      yield Time.at(hour)
      hour += increment
    end
  end
end

app/views/assignments/index.html.haml
%h1 Assignments#index
%p Find me in app/views/assignments/index.html.haml

= form_for :assignment, url: profile_assignments_path, html: {class: 'form-inline'} do |f|
  = f.text_field :recipient, placeholder: "Assignment's email address"
  = f.submit "Create Assignment", class: 'btn'

%table.assignments.table
  %tbody
    - @assignments.each do |assignment|
      %tr.assignment
        %td.recipient
          = assignment.recipients.map(&:email).join(',')
        %td.action
          = link_to :show, profile_assignment_path(assignment)
          = link_to :schedule, schedule_profile_assignment_path(id: assignment)
          = link_to :delete, profile_assignment_path(assignment), method: :delete

app/views/assignments/show.html.haml
%h1 Assignments#show
%p Find me in app/views/assignments/show.html.haml

.assignment
  %span.recipients
    = @assignment.recipients.map(&:email).join(',')
  %span.schedule_start
    = @assignment.schedule_start_at.in_time_zone(@zone).to_s(:long)
  %span
    = link_to :schedule, schedule_profile_assignment_path(@assignment, amount: 10)

  %table.availability.table
    %thead
      %tr
        %th Time
        %th Status
        %th Actions

    %tbody
      - if @meetings.present?
        - iterate(@meetings) do |time|
          %tr.day
            - if meeting = matched(@meetings, @zone, time)
              %td= meeting.display_times
              %td= meeting.state
              %td
                = reject_link_for(meeting)
                = schedule_link_for(meeting)
            - else
              %td{colspan: 3}= time.to_s(:long)